from django.conf.urls import url
from . import views
from app.views import *

urlpatterns = [
	#url(r'^admin/home/$',views.Admin,name='Admin'),
	url(r'^check/$',Check.as_view()),
	url(r'^admin/home/$',Admin.as_view()),
	#url(r'^admin/books/$',views.AllBooks,name='AllBooks'),
	url(r'^admin/books/$',AdminBooks.as_view()),
	#url(r'^admin/addbook/$',views.AddBook,name='AddBook'),
	url(r'^admin/addbook/$',AddBook.as_view()),
    #url(r'^admin/editbook/$',views.EditBook,name='EditBook'),
    url(r'^admin/editbook/$',EditBook.as_view()),
    #url(r'^admin/updatebook/$',views.UpdateBook,name='UpdateBook'),
    url(r'^admin/updatebook/$',EditBook.as_view()),
    #url(r'^admin/addnew/$',views.NewBook,name='NewBook'),
    url(r'^admin/process_requests/$',ProcessRequests.as_view()),
    url(r'^admin/discard_request/$',DiscardRequest.as_view()),    
    url(r'^admin/approve_request/$',ApproveRequest.as_view()),
	#url(r'^admin/deletebook/$',views.DeleteBook,name='DeleteBook'),
	url(r'^admin/deletebook/$',DeleteBook.as_view()),
	#url(r'^admin/users/$',views.AllUsers,name='AllUsers'),
	url(r'^admin/users/$',Users.as_view()),
	#url(r'^admin/adduser/$',views.AddUser,name='AddUser'),
	url(r'^admin/adduser/$',AddUser.as_view()),
	#url(r'^admin/edituser/$',views.EditUser,name='EditUser'),
	url(r'^admin/edituser/$',EditUser.as_view()),
	#url(r'^admin/updateuser/$',views.UpdateUser,name='UpdateUser'),
	url(r'^admin/updateuser/$',EditUser.as_view()),
	#url(r'^admin/deleteuser/$',views.DeleteUser,name='DeleteUser'),
	url(r'^admin/deleteuser/$',DeleteUser.as_view()),
	#url(r'^register/$',MemberRegistration.as_view()),
	url(r'^register/$',MemberRegistration.as_view()),
	url(r'^response_success/$',ResponseSuccess.as_view()),
	#url(r'^register/$',views.MemberRegistration,name='MemberRegistration'),
	#url(r'^login/$',views.UserLogin,name='UserLogin'),
	url(r'^login/$',UserLogin.as_view()),
	#url(r'^logout/$',views.Logout,name='Logout'),
	url(r'^logout/$',Logout.as_view()),
	url(r'^user/books/$',UserBooks.as_view()),
	#url(r'^user/books/$',views.AllBooks,name='AllBooks'),
	#url(r'^user/home/$',views.UserProfile,name='UserProfile'),
	url(r'^user/home/$',UserHome.as_view()),
	#url(r'^user/issue_details',views.Issue_Details,name='Issue_Details'),
	url(r'^user/issue_details',IssueDetails.as_view()),
	url(r'^user/pending_details/$',PendingDetails.as_view()),
	#url(r'^user/pending_details/$',views.Pending,name='Pending'),
	url(r'^user/request_issue/$',RequestIssue.as_view()),
	#url(r'^user/request_issue/$',views.RequestIssue,name='RequestIssue'),
]